version: '1.0'
name: pipeline-20260306
displayName: pipeline-20260306
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-1e13d033
    displayName: 后端构建
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - '# 可以使用pip下载依赖'
          - '# pip install --user -r requirements.txt'
          - pwd
          - ls -la
          - python --version
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches: []
        notify: []
        strategy:
          retry: '0'
  - name: stage-5fa4b636
    displayName: docker
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: crpi-76fbd77t4270ljs4.cn-hangzhou.personal.cr.aliyuncs.com/xueyang_me
        username: davindai@hotmail.com
        password: Pp70027784
        tag: ${GITEE_PIPELINE_BUILD_NUMBER}
        dockerfile: backend/Dockerfile
        context: ''
        artifacts: []
        isCache: false
        processorType:
          - amd64
        parameter: {}
        notify: []
        strategy:
          retry: '0'
